name: Update data

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch latest market data
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
          CB_SHEETS_CSV_URL: ${{ secrets.CB_SHEETS_CSV_URL }}
        run: |
          python fetch_data.py

      - name: Commit and push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json 2>/dev/null || true
          git add data/cb_sheets.json 2>/dev/null || true
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "chore: update market data"
            git push
          else
            echo "No changes to commit"
          fi
